"""Configuration module for ISCIACUS Monitoring Backend."""

from config.messages import (
    BOT_FB_BLOCKED,
    BOT_FB_CLOUDFLARE_CHALLENGE,
    BOT_PROTECTION_BLOCKING,
    BOT_PROTECTION_OK,
    GSC_META_DESC_MISSING,
    GSC_META_DESC_SHORT,
    GSC_META_TITLE_MISSING,
    GSC_META_TITLE_SHORT,
    GSC_ROBOTS_DISALLOW_ALL,
    GSC_ROBOTS_NO_SITEMAP,
    GSC_ROBOTS_NOT_FOUND,
    GSC_SITEMAP_FEW_URLS,
    format_message,
)


__all__ = [
    "BOT_FB_BLOCKED",
    "BOT_FB_CLOUDFLARE_CHALLENGE",
    "BOT_PROTECTION_BLOCKING",
    "BOT_PROTECTION_OK",
    "GSC_META_DESC_MISSING",
    "GSC_META_DESC_SHORT",
    "GSC_META_TITLE_MISSING",
    "GSC_META_TITLE_SHORT",
    "GSC_ROBOTS_DISALLOW_ALL",
    "GSC_ROBOTS_NOT_FOUND",
    "GSC_ROBOTS_NO_SITEMAP",
    "GSC_SITEMAP_FEW_URLS",
    "format_message",
]
